### PR TITLE
Move babel-runtime to peer dependencies

### PR DESCRIPTION
**Pull request by lemieux**
Not sure if `>= 5.8.0` is too lenient ¯\_(ツ)_/¯

I kept it in the devDependencies to make sure it's there for local development.

What do you think @dozoisch ?

### CODE REVIEW

**Comment by dozoisch** [comment]
I think it should be fine! I just hope there are no incompatibilities between the two version in what is used!

**Comment by dozoisch** [comment]
Published as 0.6.0! let me know if everything works properly

**Comment by lemieux** [comment]
Thanks! I'll try that right away :)

**Comment by lemieux** [comment]
Works perfectly. Thanks again!

**Pull request merged**
